# Generated by Django 3.0.1 on 2019-12-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gra', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='image',
            new_name='game',
        ),
    ]
