# Generated by Django 3.0.1 on 2019-12-28 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gra', '0002_auto_20191228_1416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
