# Generated by Django 3.0.1 on 2019-12-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gra', '0003_delete_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nazwa')),
                ('published', models.DateTimeField(verbose_name='Data publikacji')),
                ('author', models.CharField(max_length=150, verbose_name='Autor')),
                ('game', models.FileField(upload_to='games', verbose_name='Gra')),
            ],
        ),
    ]
